name: cwokral
favicon: null
layout_spectrum: 0.41458
typography_spectrum: 0.466094394447282
title: Exploring The Grid
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0C0F18'
    - '#F3FFFF'
    - '#7F817C'
    - '#36555A'
    - '#A5BFE0'
  brandStrength: 0.6817490856628865
  lightness: 1
  saturation: 0.2247742
  rhythmicContrast: 0.4676905
purpose: []
